!
! automatically generated from sim_class.py
!
module mod_params
use mod_prec
implicit none
   character(*), parameter :: home_dir = '/home/jripley/teuk-fortran-2020'
   character(*), parameter :: run_type = 'basic_run'
   logical, parameter :: debug = .false.
   real(rp), parameter :: black_hole_mass = 0.5_rp
   real(rp), parameter :: black_hole_spin = 0.499_rp
   real(rp), parameter :: compactification_length = 1.0_rp
   real(rp), parameter :: evolve_time = 150.0_rp
   integer(ip), parameter :: num_saved_times = 500_ip
   integer(ip), parameter :: nx = 192_ip
   integer(ip), parameter :: nl = 36_ip
   logical, parameter :: metric_recon = .true.
   logical, parameter :: scd_order = .true.
   logical, parameter :: constrained_evo = .true.
   logical, parameter :: write_indep_res = .true.
   logical, parameter :: write_metric_recon_fields = .false.
   logical, parameter :: write_scd_order_source = .true.
   logical, parameter :: write_coefs = .false.
   character(*), parameter :: computer = 'home'
   character(*), parameter :: della_out_stem = '/tigress/jripley/tf-out/'
   character(*), parameter :: walltime = '144:00:00'
   character(*), parameter :: memory = '2048'
   character(*), parameter :: email = 'lloydripley@gmail.com'
   integer(ip), parameter :: psi_spin = -2_ip
   integer(ip), parameter :: psi_boost = -2_ip
   real(rp), parameter :: start_multiple = 1.0_rp
   integer(ip), parameter :: pm1_ang = 2_ip
   integer(ip), parameter :: l_ang_pm1 = 2_ip
   character(*), parameter :: initial_data_direction_pm1 = 'ingoing'
   real(rp), parameter :: amp_re_pm1 = 0.1_rp
   real(rp), parameter :: amp_im_pm1 = 0.0_rp
   real(rp), parameter :: rl_pm1_0 = 1.1_rp
   real(rp), parameter :: ru_pm1_0 = 2.5_rp
   integer(ip), parameter :: l_ang_nm1 = 2_ip
   character(*), parameter :: initial_data_direction_nm1 = 'ingoing'
   real(rp), parameter :: amp_re_nm1 = 0.0_rp
   real(rp), parameter :: amp_im_nm1 = 0.0_rp
   real(rp), parameter :: rl_nm1_0 = 1.1_rp
   real(rp), parameter :: ru_nm1_0 = 2.5_rp
   integer(ip), parameter :: pm2_ang = 3_ip
   integer(ip), parameter :: l_ang_pm2 = 3_ip
   character(*), parameter :: initial_data_direction_pm2 = 'ingoing'
   real(rp), parameter :: amp_re_pm2 = 0.0_rp
   real(rp), parameter :: amp_im_pm2 = 0.0_rp
   real(rp), parameter :: rl_pm2_0 = -1.5_rp
   real(rp), parameter :: ru_pm2_0 = 1.5_rp
   integer(ip), parameter :: l_ang_nm2 = 3_ip
   character(*), parameter :: initial_data_direction_nm2 = 'ingoing'
   real(rp), parameter :: amp_re_nm2 = 0.0_rp
   real(rp), parameter :: amp_im_nm2 = 0.0_rp
   real(rp), parameter :: rl_nm2_0 = -1.5_rp
   real(rp), parameter :: ru_nm2_0 = 1.5_rp
   integer(ip), dimension(2), parameter :: lin_m = [2_ip,-2_ip]
   integer(ip), dimension(3), parameter :: scd_m = [0_ip,-4_ip,4_ip]
   integer(ip), dimension(2), parameter :: lin_write_m = [2_ip,-2_ip]
   integer(ip), dimension(3), parameter :: scd_write_m = [0_ip,-4_ip,4_ip]
   integer(ip), parameter :: max_l = 35_ip
   real(rp), parameter :: horizon = 0.5316069612585582_rp
   real(rp), parameter :: R_max = 1.8810889865560452_rp
   real(rp), parameter :: rl_pm1 = 0.584767657384414_rp
   real(rp), parameter :: ru_pm1 = 1.3290174031463955_rp
   real(rp), parameter :: rl_nm1 = 0.584767657384414_rp
   real(rp), parameter :: ru_nm1 = 1.3290174031463955_rp
   real(rp), parameter :: rl_pm2 = -0.7974104418878374_rp
   real(rp), parameter :: ru_pm2 = 0.7974104418878374_rp
   real(rp), parameter :: rl_nm2 = -0.7974104418878374_rp
   real(rp), parameter :: ru_nm2 = 0.7974104418878374_rp
   real(rp), parameter :: constraint_damping = 447.21348369659154_rp
   real(rp), parameter :: scd_order_start_time = 6.854804695047969_rp
   integer(ip), dimension(1), parameter :: lin_pos_m = [2_ip]
   integer(ip), parameter :: len_lin_pos_m = 1_ip
   integer(ip), parameter :: len_lin_m = 2_ip
   integer(ip), parameter :: len_scd_m = 3_ip
   integer(ip), parameter :: len_lin_write_m = 2_ip
   integer(ip), parameter :: len_scd_write_m = 3_ip
   integer(ip), parameter :: num_threads = 1_ip
   integer(ip), parameter :: ny = 50_ip
   real(rp), parameter :: dt = 0.000244140625_rp
   integer(ip), parameter :: nt = 307200_ip
   integer(ip), parameter :: t_step_save = 614_ip
   integer(ip), parameter :: max_m = 4_ip
   integer(ip), parameter :: min_m = -4_ip
   integer(ip), parameter :: max_s = 3_ip
   integer(ip), parameter :: min_s = -3_ip
   character(*), parameter :: output_stem = 'Oct_24_17_06_15_m0.5_s0.499_nx192_nl36'
   character(*), parameter :: output_dir = 'output/Oct_24_17_06_15_m0.5_s0.499_nx192_nl36'
   character(*), parameter :: bin_name = 'Oct_24_17_06_15_m0.5_s0.499_nx192_nl36.run'
   character(*), parameter :: tables_dir = 'output/Oct_24_17_06_15_m0.5_s0.499_nx192_nl36/tables'
end module mod_params
